name: C/C++ CI

on:
  push:
    branches: [ master greyblue9/develop ]
  pull_request:
    branches: [ master greyblue9/develop ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: sudo apt-get install -y libncurses-dev libncursesw5-dev
    - name: configure
      run: chmod 0755 configure && mkdir build && cd build && $PWD/../configure
    - name: make
      run: cd build && make LDFLAGS=-Wl,-z,muldefs


#